"""Tests for report generator and comparator."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
import yaml

from msg_embedding.report import MultiRunComparator, ReportGenerator


def _write_fake_run(
    tmp_path: Path,
    run_id: str,
    *,
    include_metrics: bool = True,
    include_tb: bool = False,
    include_embeddings: bool = False,
) -> tuple[Path, Path]:
    artifacts_dir = tmp_path / "artifacts"
    reports_dir = tmp_path / "reports"
    run_artifacts = artifacts_dir / run_id
    run_reports = reports_dir / run_id
    run_artifacts.mkdir(parents=True, exist_ok=True)
    run_reports.mkdir(parents=True, exist_ok=True)

    (run_artifacts / "metadata.json").write_text(
        json.dumps(
            {
                "run_id": run_id,
                "git_sha": "abc1234",
                "timestamp": "2026-04-17T00:00:00Z",
                "ckpt": f"artifacts/{run_id}/best.pth",
            }
        ),
        encoding="utf-8",
    )
    (run_artifacts / "config.yaml").write_text(
        yaml.safe_dump(
            {
                "train": {"batch_size": 32, "learning_rate": 1e-4, "epochs": 20},
                "model": {"embed_dim": 64, "depth": 4},
            }
        ),
        encoding="utf-8",
    )
    if include_metrics:
        (run_reports / "metrics.json").write_text(
            json.dumps(
                {
                    "ct": 0.87,
                    "tw": 0.85,
                    "knn_consistency": 0.72,
                    "nmse_db": -18.5,
                    "cos_clean_noisy_mean": 0.93,
                    "cos_cross_ue_mean": 0.12,
                    "meta": {
                        "run_id": run_id,
                        "ckpt": f"artifacts/{run_id}/best.pth",
                        "git_sha": "abc1234",
                        "timestamp": "2026-04-17T00:00:00Z",
                    },
                }
            ),
            encoding="utf-8",
        )
    if include_tb:
        tb_dir = run_artifacts / "tb"
        tb_dir.mkdir(parents=True, exist_ok=True)
        try:
            from torch.utils.tensorboard import SummaryWriter

            writer = SummaryWriter(log_dir=str(tb_dir))
            for step in range(5):
                writer.add_scalar("loss/train", 1.0 / (step + 1), step)
            writer.flush()
            writer.close()
        except ImportError:
            pass
    if include_embeddings:
        pytest.importorskip("pyarrow")
        import pandas as pd

        n, d = 30, 8
        rng = np.random.default_rng(0)
        z = rng.standard_normal((n, d)).astype(np.float32)
        df = pd.DataFrame({f"z_{i}": z[:, i] for i in range(d)})
        df["sinr_dB"] = rng.uniform(-5, 20, size=n).astype(np.float32)
        df["link"] = rng.choice(["UL", "DL"], size=n)
        df["source"] = "synthetic"
        df.to_parquet(run_artifacts / "embeddings.parquet")
    return artifacts_dir, reports_dir


def test_build_minimal_report(tmp_path: Path) -> None:
    artifacts_dir, reports_dir = _write_fake_run(tmp_path, "runA")
    gen = ReportGenerator("runA", artifacts_dir=artifacts_dir, reports_dir=reports_dir)
    out_path = gen.build()
    assert out_path.exists()
    html = out_path.read_text(encoding="utf-8")
    assert "runA" in html
    assert "Hyperparameters" in html
    assert "Metrics" in html
    assert "Training curves" in html
    assert "Latent UMAP" in html
    assert "Generated by msg_embedding Phase 4" in html
    assert "0.8700" in html or "0.87" in html


def test_build_missing_metrics_renders_na(tmp_path: Path) -> None:
    artifacts_dir, reports_dir = _write_fake_run(tmp_path, "runB", include_metrics=False)
    gen = ReportGenerator("runB", artifacts_dir=artifacts_dir, reports_dir=reports_dir)
    out_path = gen.build()
    html = out_path.read_text(encoding="utf-8")
    assert "N/A" in html
    assert "runB" in html


def test_build_is_idempotent(tmp_path: Path) -> None:
    artifacts_dir, reports_dir = _write_fake_run(tmp_path, "runC")
    gen = ReportGenerator("runC", artifacts_dir=artifacts_dir, reports_dir=reports_dir)
    first = gen.build().read_text(encoding="utf-8")
    second = gen.build().read_text(encoding="utf-8")
    assert first == second


def test_build_with_embeddings(tmp_path: Path) -> None:
    try:
        import pandas as pd  # noqa: F401
    except ImportError:
        pytest.skip("pandas not available")
    try:
        artifacts_dir, reports_dir = _write_fake_run(
            tmp_path, "runD", include_embeddings=True
        )
    except Exception as exc:
        pytest.skip(f"parquet backend unavailable: {exc}")
    gen = ReportGenerator("runD", artifacts_dir=artifacts_dir, reports_dir=reports_dir)
    out_path = gen.build()
    html = out_path.read_text(encoding="utf-8")
    assert "runD" in html
    assert "No embeddings.parquet available" not in html


def test_auto_creates_output_dir(tmp_path: Path) -> None:
    artifacts_dir = tmp_path / "art"
    reports_dir = tmp_path / "rep"
    (artifacts_dir / "runE").mkdir(parents=True)
    (artifacts_dir / "runE" / "metadata.json").write_text("{}", encoding="utf-8")
    gen = ReportGenerator("runE", artifacts_dir=artifacts_dir, reports_dir=reports_dir)
    out_path = gen.build()
    assert out_path.exists()
    assert (reports_dir / "runE").is_dir()


def test_compare_renders_side_by_side(tmp_path: Path) -> None:
    artifacts_dir, reports_dir = _write_fake_run(tmp_path, "runX")
    _write_fake_run(tmp_path, "runY")
    comparator = MultiRunComparator(
        artifacts_dir=artifacts_dir, reports_dir=reports_dir
    )
    out_path = comparator.compare(["runX", "runY"])
    assert out_path.exists()
    html = out_path.read_text(encoding="utf-8")
    assert "runX" in html
    assert "runY" in html
    assert "multi-run comparison" in html.lower()


def test_compare_missing_metrics_na(tmp_path: Path) -> None:
    artifacts_dir, reports_dir = _write_fake_run(
        tmp_path, "runM", include_metrics=False
    )
    _write_fake_run(tmp_path, "runN", include_metrics=False)
    comparator = MultiRunComparator(
        artifacts_dir=artifacts_dir, reports_dir=reports_dir
    )
    out_path = comparator.compare(["runM", "runN"])
    html = out_path.read_text(encoding="utf-8")
    assert "N/A" in html
